feat: create braavos resolver draft
starknet-id/resolver_delegation pull request #1
Opened 2023-01-17 21:42 UTC by 0xBenaparte

2023-01-19 20:42 UTC, Th0rgal requested changes
Très clean, en particulier les tests. Je suggère d'interdire de transférer à un compte qui n'est pas braavos, histoire de rester cohérent avec le mint.

2023-01-20 07:02 UTC, 0xBenaparte commented
> Très clean, en particulier les tests. Je suggère d'interdire de transférer à un compte qui n'est pas braavos, histoire de rester cohérent avec le mint.

Pas con je leur demande direct

2023-01-20 07:10 UTC, 0xBenaparte commented
> > Très clean, en particulier les tests. Je suggère d'interdire de transférer à un compte qui n'est pas braavos, histoire de rester cohérent avec le mint.
> 
> Pas con je leur demande direct

J'ai rajouté le changement !

2023-01-20 08:23 UTC, Th0rgal approved these changes
Good, pense à appeler tes stop_mock avec des noms différents et les appeler en fin de hint

2023-01-20 09:38 UTC, merged